{% set name = "onnxoptimizer" %}
{% set version = "0.3.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/onnxoptimizer-{{ version }}.tar.gz
  sha256: e08b726e0d4577e51e529f36bc324bf11b7cff12852cf3eee081f05c8b8c6f33

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  build:
    - cmake
    - make
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - pytest-runner
  run:
    - python
    - onnx

test:
  imports:
    - onnxoptimizer
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/onnx/optimizer
  summary: Actively maintained ONNX Optimizer
  license: Apache-2.0
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - neNasko1
