{% set name = "onnxoptimizer" %}
{% set version = "0.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/onnxoptimizer-{{ version }}.tar.gz
  sha256: c912f96847450e869b179a7b460b8aeda7fd3cdf7da4dda7f011bf7f923f3128

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - cmake
    - make
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - pytest-runner
  run:
    - python
    - onnx

test:
  imports:
    - onnxoptimizer
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/onnx/optimizer
  summary: Actively maintained ONNX Optimizer
  license: Apache-2.0
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - neNasko1
